CSV_LOADER_CLASSES = ['csv_loader_classes.institution_loader.InstitutionLoader',
                      'csv_loader_classes.program_loader.ProgramLoader',
                      'csv_loader_classes.course_type_loader.CourseTypeLoader',
                      'csv_loader_classes.course_section_students_status_loader.CourseSectionStudentsStatusLoader',
                      'csv_loader_classes.user_type_loader.UserTypeLoader',
                      'csv_loader_classes.users_loader.UsersLoader',
                      'csv_loader_classes.courses_loader.CoursesLoader',
                      'csv_loader_classes.course_sections_loader.CourseSectionsLoader',
                      'csv_loader_classes.section_times_loader.SectionTimesLoader',
                      'csv_loader_classes.user_type_destinations_loader.UserTypeDestinationsLoader',
                      'csv_loader_classes.user_type_destinations_user_type_loader.UserTypeDestinationsUserTypeLoader',
                      'csv_loader_classes.course_section_students_loader.CourseSectionsStudentsLoader']
